package SynthLang.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cd74L, "SynthLang.structure.Connection"))) {
        return Collections.<ConceptEditor>singletonList(new Connection_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d4ecL, "SynthLang.structure.ConnectionList"))) {
        return Collections.<ConceptEditor>singletonList(new ConnectionList_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x4854ee8f94d75fbcL, "SynthLang.structure.ControlButton"))) {
        return Collections.<ConceptEditor>singletonList(new ControlButton_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e811ca259L, "SynthLang.structure.ControlConnection"))) {
        return Collections.<ConceptEditor>singletonList(new ControlConnection_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x4854ee8f94d7536fL, "SynthLang.structure.ControlKnob"))) {
        return Collections.<ConceptEditor>singletonList(new ControlKnob_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x4854ee8f94d75d33L, "SynthLang.structure.ControlSlider"))) {
        return Collections.<ConceptEditor>singletonList(new ControlSlider_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x4854ee8f94deb9daL, "SynthLang.structure.MainPanel"))) {
        return Collections.<ConceptEditor>singletonList(new MainPanel_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e80b0127aL, "SynthLang.structure.Port"))) {
        return Collections.<ConceptEditor>singletonList(new Port_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x73ae09d1ab6f50fbL, "SynthLang.structure.SoundConnectionAdd"))) {
        return Collections.<ConceptEditor>singletonList(new SoundConnectionAdd_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e80b8f2b1L, "SynthLang.structure.SoundGeneratorImpulse"))) {
        return Collections.<ConceptEditor>singletonList(new SoundGeneratorImpulse_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e80b038efL, "SynthLang.structure.SoundGeneratorSawTooth"))) {
        return Collections.<ConceptEditor>singletonList(new SoundGeneratorSawTooth_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e80b77662L, "SynthLang.structure.SoundGeneratorSawToothBL"))) {
        return Collections.<ConceptEditor>singletonList(new SoundGeneratorSawToothBL_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e80b77861L, "SynthLang.structure.SoundGeneratorSawToothDPW"))) {
        return Collections.<ConceptEditor>singletonList(new SoundGeneratorSawToothDPW_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e80b03a93L, "SynthLang.structure.SoundGeneratorSine"))) {
        return Collections.<ConceptEditor>singletonList(new SoundGeneratorSine_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e80c2596aL, "SynthLang.structure.SoundLineOut"))) {
        return Collections.<ConceptEditor>singletonList(new SoundLineOut_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d50bL, "SynthLang.structure.SoundList"))) {
        return Collections.<ConceptEditor>singletonList(new SoundList_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc63c92L, "SynthLang.structure.SubPanel"))) {
        return Collections.<ConceptEditor>singletonList(new SubPanel_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, "SynthLang.structure.Synthesizer"))) {
        return Collections.<ConceptEditor>singletonList(new Synthesizer_Editor());
      }
    }
    return Collections.<ConceptEditor>emptyList();
  }

  public Collection<ConceptEditorComponent> getDeclaredEditorComponents(SAbstractConcept concept, String editorComponentId) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d475L, "SynthLang.structure.AbstractGuiElement"))) {
        if ("SynthLang.editor.ControlParameters_component".equals(editorComponentId)) {
          return Collections.<ConceptEditorComponent>singletonList(new ControlParameters_component());
        }
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cd4aL, "SynthLang.structure.AbstractSound"))) {
        if ("SynthLang.editor.Sound_component".equals(editorComponentId)) {
          return Collections.<ConceptEditorComponent>singletonList(new Sound_component());
        }
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getInterfaceConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x42b9a3d32329ad49L, "SynthLang.structure.IPanel"))) {
        if ("SynthLang.editor.PanelParameters_component".equals(editorComponentId)) {
          return Collections.<ConceptEditorComponent>singletonList(new PanelParameters_component());
        }
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e80b0127aL, "SynthLang.structure.Port"))) {
        if ("SynthLang.editor.PortParameters_component".equals(editorComponentId)) {
          return Collections.<ConceptEditorComponent>singletonList(new PortParameters_component());
        }
      }
    }
    return Collections.<ConceptEditorComponent>emptyList();
  }


}
