package SynthLang.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cd74L, "SynthLang.structure.Connection"))) {
        return Collections.<ConceptEditor>singletonList(new Connection_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d4ecL, "SynthLang.structure.ConnectionList"))) {
        return Collections.<ConceptEditor>singletonList(new ConnectionList_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x4854ee8f94d75fbcL, "SynthLang.structure.ControlButton"))) {
        return Collections.<ConceptEditor>singletonList(new ControlButton_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x4854ee8f94d7536fL, "SynthLang.structure.ControlKnob"))) {
        return Collections.<ConceptEditor>singletonList(new ControlKnob_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x4854ee8f94d75d33L, "SynthLang.structure.ControlSlider"))) {
        return Collections.<ConceptEditor>singletonList(new ControlSlider_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x4854ee8f94deb9daL, "SynthLang.structure.MainPanel"))) {
        return Collections.<ConceptEditor>singletonList(new MainPanel_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cd4aL, "SynthLang.structure.Sound"))) {
        return Collections.<ConceptEditor>singletonList(new Sound_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d50bL, "SynthLang.structure.SoundList"))) {
        return Collections.<ConceptEditor>singletonList(new SoundList_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc63c92L, "SynthLang.structure.SubPanel"))) {
        return Collections.<ConceptEditor>singletonList(new SubPanel_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, "SynthLang.structure.Synthesizer"))) {
        return Collections.<ConceptEditor>singletonList(new Synthesizer_Editor());
      }
    }
    return Collections.<ConceptEditor>emptyList();
  }

  public Collection<ConceptEditorComponent> getDeclaredEditorComponents(SAbstractConcept concept, String editorComponentId) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d475L, "SynthLang.structure.AbstractGuiElement"))) {
        if ("SynthLang.editor.ControlParameters".equals(editorComponentId)) {
          return Collections.<ConceptEditorComponent>singletonList(new ControlParameters());
        }
      }
    }
    return Collections.<ConceptEditorComponent>emptyList();
  }


}
