package SynthLang.sandbox;

/*Generated by MPS */


/**
 * Interface for all Synthetica Models
 */
public interface ISimpleSynth {

  /**
   * Startup method for a synthesizer
   */
  public void start();

  /**
   * Shutdown method for a synthesizer
   */
  public void stop();
}
