package SynthLang.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JRootPane;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import java.awt.event.ActionEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowAdapter;

public class SimpleSynthController {

  private SimpleSynthModel syntheticaModel = null;
  private SimpleSynthView syntheticaFrame = null;

  /**
   * This Controller generates and handles the communication between the program logic and the user interface.
   */
  public SimpleSynthController() {
    try {
      syntheticaModel = new SimpleSynthModel();
      syntheticaFrame = new SimpleSynthView(this);
    } catch (Exception e) {
      System.err.println("Failed to initialize user interface.");
      e.printStackTrace();
      if (syntheticaModel != null) {
        syntheticaModel.stop();
      }
      System.exit(0);
    }
    installExitHandler(syntheticaFrame, syntheticaModel);
    installEscapeCloseOperation(syntheticaFrame);
    syntheticaModel.start();
  }

  /**
   * Install event handler for window closing action if ESC-key is pressed.
   * 
   * @param frame the frame of the main window
   */
  public static void installEscapeCloseOperation(final JFrame frame) {
    JRootPane root = frame.getRootPane();
    root.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "CLOSE_WINDOW_ACTION");
    root.getActionMap().put("CLOSE_WINDOW_ACTION", new AbstractAction() {
      /**
       * AbstractAction is serializable
       */
      private static final long serialVersionUID = 2847198638476373364L;
      @Override
      public void actionPerformed(ActionEvent event) {
        System.out.println("close with ESC" + event);
        frame.dispatchEvent(new WindowEvent(frame, WindowEvent.WINDOW_CLOSING));
      }
    });
  }

  /**
   * Install exit handler
   * 
   * @param frame the frame of the main window
   * @param model the Synthetica model
   */
  private static <T extends ISimpleSynth> void installExitHandler(final JFrame frame, final T model) {
    frame.addWindowListener(new WindowAdapter() {
      @Override
      public void windowClosing(WindowEvent evt) {
        model.stop();
        System.exit(0);
      }
    });
  }

  /*package*/ SimpleSynthModel getModel() {
    return syntheticaModel;
  }
}
