package SynthLang.sandbox;

/*Generated by MPS */

import javax.swing.JApplet;
import javax.swing.SwingUtilities;

/**
 * This class represents the main class of the Synthetica program.
 * 
 * @author Gerhard Aigner
 * @author Martin Duregger
 * @version 1.0.0
 */
public class SimpleSynth extends JApplet {

  public static void main(final String[] args) {
    SwingUtilities.invokeLater(new Runnable() {
      public void run() {
        new SimpleSynthController();
      }
    });
  }
}
