package SynthLang.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.generator.template.IfMacroContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.internal.collections.runtime.ITranslator2;

@Generated
public class QueriesGenerated {
  public static boolean baseMappingRule_Condition_3340082741257730295(final BaseMappingRuleContext _context) {
    return SPropertyOperations.getBoolean_def(_context.getNode(), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e80b0127aL, 0x2e5a5b8e80b1e952L, "hasConfig"), "false");
  }
  public static boolean baseMappingRule_Condition_4808054204418332164(final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x4854ee8f94d75d33L, 0x42b9a3d3232c4446L, "orientation"), "\"VERTICAL\"", "\"HORIZONTAL\"");
  }
  public static Object propertyMacro_GetPropertyValue_3340082741245520612(final PropertyMacroContext _context) {
    String result = SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    if (result != null) {
      result = result.replaceAll("[^_\\p{Alnum}]", "");
      if (result.substring(0, 1).matches("\\p{Digit}")) {
        result = "_" + result;
      }
    } else {
      result = "Synthetica";
    }
    return result;
  }
  public static Object propertyMacro_GetPropertyValue_3340082741250213399(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_3340082741245607651(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_3340082741249818934(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, 0x43fe12378cc7ccf4L, "userInterface")), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x4854ee8f94deb9daL, 0x4854ee8f94dec2c8L, "width"));
  }
  public static Object propertyMacro_GetPropertyValue_3340082741249834178(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, 0x43fe12378cc7ccf4L, "userInterface")), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x4854ee8f94deb9daL, 0x4854ee8f94dec2f7L, "height"));
  }
  public static Object propertyMacro_GetPropertyValue_3347507059715185615(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, 0x43fe12378cc7ccf4L, "userInterface")), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x42b9a3d32329ad49L, 0x42b9a3d32329adbaL, "columns"));
  }
  public static Object propertyMacro_GetPropertyValue_3347507059715194933(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, 0x43fe12378cc7ccf4L, "userInterface")), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x42b9a3d32329ad49L, 0x42b9a3d32329addfL, "rows"));
  }
  public static Object propertyMacro_GetPropertyValue_3347507059714836362(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, 0x43fe12378cc7ccf4L, "userInterface")), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x42b9a3d32329ad49L, 0x42b9a3d32329adbaL, "columns")) - 1;
  }
  public static Object propertyMacro_GetPropertyValue_3347507059714835298(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, 0x43fe12378cc7ccf4L, "userInterface")), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x42b9a3d32329ad49L, 0x42b9a3d32329addfL, "rows")) - 1;
  }
  public static Object propertyMacro_GetPropertyValue_3340082741245531120(final PropertyMacroContext _context) {
    String result = SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    if (result != null) {
      result = result.replaceAll("[^_\\p{Alnum}]", "");
      if (result.substring(0, 1).matches("\\p{Digit}")) {
        result = "_" + result;
      }
    } else {
      result = "Synthetica";
    }
    return result + "View";
  }
  public static Object propertyMacro_GetPropertyValue_3340082741245521718(final PropertyMacroContext _context) {
    String result = SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    if (result != null) {
      result = result.replaceAll("[^_\\p{Alnum}]", "");
      if (result.substring(0, 1).matches("\\p{Digit}")) {
        result = "_" + result;
      }
    } else {
      result = "Synthetica";
    }
    return result + "Controller";
  }
  public static Object propertyMacro_GetPropertyValue_3340082741245498499(final PropertyMacroContext _context) {
    String result = SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    if (result != null) {
      result = result.replaceAll("[^_\\p{Alnum}]", "");
      if (result.substring(0, 1).matches("\\p{Digit}")) {
        result = "_" + result;
      }
    } else {
      result = "Synthetica";
    }
    return "I" + result;
  }
  public static Object propertyMacro_GetPropertyValue_3340082741245526486(final PropertyMacroContext _context) {
    String result = SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    if (result != null) {
      result = result.replaceAll("[^_\\p{Alnum}]", "");
      if (result.substring(0, 1).matches("\\p{Digit}")) {
        result = "_" + result;
      }
    } else {
      result = "Synthetica";
    }
    return result + "Model";
  }
  public static Object propertyMacro_GetPropertyValue_3340082741249862205(final PropertyMacroContext _context) {
    return _context.createUniqueName("knobInputModel", null);
  }
  public static Object propertyMacro_GetPropertyValue_3340082741250101044(final PropertyMacroContext _context) {
    return _context.createUniqueName("knob", null);
  }
  public static Object propertyMacro_GetPropertyValue_3340082741250088016(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_3340082741250113132(final PropertyMacroContext _context) {
    return _context.createUniqueName("knobPanel", null);
  }
  public static Object propertyMacro_GetPropertyValue_3347507059715248400(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d475L, 0x4854ee8f94d7594bL, "gridPosX"));
  }
  public static Object propertyMacro_GetPropertyValue_3347507059715248806(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d475L, 0x4854ee8f94d75af9L, "gridPosY"));
  }
  public static Object propertyMacro_GetPropertyValue_3347507059715249219(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d475L, 0x4854ee8f94d75898L, "spanX"));
  }
  public static Object propertyMacro_GetPropertyValue_3347507059715249632(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d475L, 0x4854ee8f94d758f0L, "spanY"));
  }
  public static Object propertyMacro_GetPropertyValue_3340082741250337361(final PropertyMacroContext _context) {
    return _context.createUniqueName("slider", null);
  }
  public static Object propertyMacro_GetPropertyValue_3340082741250407510(final PropertyMacroContext _context) {
    return _context.createUniqueName("sliderPanel", null);
  }
  public static Object propertyMacro_GetPropertyValue_8335610756438754087(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_3340082741250426081(final PropertyMacroContext _context) {
    return _context.createUniqueName("sliderLabel", null);
  }
  public static Object propertyMacro_GetPropertyValue_3347507059715256091(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d475L, 0x4854ee8f94d7594bL, "gridPosX"));
  }
  public static Object propertyMacro_GetPropertyValue_3347507059715256104(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d475L, 0x4854ee8f94d75af9L, "gridPosY"));
  }
  public static Object propertyMacro_GetPropertyValue_3347507059715256117(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d475L, 0x4854ee8f94d75898L, "spanX"));
  }
  public static Object propertyMacro_GetPropertyValue_3347507059715256130(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d475L, 0x4854ee8f94d758f0L, "spanY"));
  }
  public static Object propertyMacro_GetPropertyValue_3340082741251010928(final PropertyMacroContext _context) {
    return _context.createUniqueName("subPanel", null);
  }
  public static Object propertyMacro_GetPropertyValue_3347507059715318000(final PropertyMacroContext _context) {
    return _context.createUniqueName("gbl", null);
  }
  public static Object propertyMacro_GetPropertyValue_3347507059715302648(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x42b9a3d32329ad49L, 0x42b9a3d32329adbaL, "columns"));
  }
  public static Object propertyMacro_GetPropertyValue_3347507059715302689(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x42b9a3d32329ad49L, 0x42b9a3d32329addfL, "rows"));
  }
  public static Object propertyMacro_GetPropertyValue_3347507059715302743(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x42b9a3d32329ad49L, 0x42b9a3d32329adbaL, "columns")) - 1;
  }
  public static Object propertyMacro_GetPropertyValue_3347507059715302760(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x42b9a3d32329ad49L, 0x42b9a3d32329addfL, "rows")) - 1;
  }
  public static Object propertyMacro_GetPropertyValue_3347507059715215475(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d475L, 0x4854ee8f94d7594bL, "gridPosX"));
  }
  public static Object propertyMacro_GetPropertyValue_3347507059715221466(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d475L, 0x4854ee8f94d75af9L, "gridPosY"));
  }
  public static Object propertyMacro_GetPropertyValue_3347507059715221909(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d475L, 0x4854ee8f94d75898L, "spanX"));
  }
  public static Object propertyMacro_GetPropertyValue_3347507059715222337(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d475L, 0x4854ee8f94d758f0L, "spanY"));
  }
  public static Object propertyMacro_GetPropertyValue_3340082741256780609(final PropertyMacroContext _context) {
    String result = SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    if (result != null) {
      result = result.replaceAll("[^_\\p{Alnum}]", "");
    } else {
      result = "";
    }
    return "sound_" + result;
  }
  public static Object propertyMacro_GetPropertyValue_8335610756436585288(final PropertyMacroContext _context) {
    String result = SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    if (result != null) {
      result = result.replaceAll("[^_\\p{Alnum}]", "");
    } else {
      result = "";
    }
    return "sound_" + result;
  }
  public static Object propertyMacro_GetPropertyValue_8335610756436586010(final PropertyMacroContext _context) {
    String result = SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    if (result != null) {
      result = result.replaceAll("[^_\\p{Alnum}]", "");
    } else {
      result = "";
    }
    return "sound_" + result;
  }
  public static Object propertyMacro_GetPropertyValue_8335610756436586538(final PropertyMacroContext _context) {
    String result = SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    if (result != null) {
      result = result.replaceAll("[^_\\p{Alnum}]", "");
    } else {
      result = "";
    }
    return "sound_" + result;
  }
  public static Object propertyMacro_GetPropertyValue_8335610756436587208(final PropertyMacroContext _context) {
    String result = SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    if (result != null) {
      result = result.replaceAll("[^_\\p{Alnum}]", "");
    } else {
      result = "";
    }
    return "sound_" + result;
  }
  public static Object propertyMacro_GetPropertyValue_8335610756436587630(final PropertyMacroContext _context) {
    String result = SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    if (result != null) {
      result = result.replaceAll("[^_\\p{Alnum}]", "");
    } else {
      result = "";
    }
    return "sound_" + result;
  }
  public static Object propertyMacro_GetPropertyValue_8335610756438484436(final PropertyMacroContext _context) {
    String result = SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    if (result != null) {
      result = result.replaceAll("[^_\\p{Alnum}]", "");
    } else {
      result = "";
    }
    return "sound_" + result;
  }
  public static Object propertyMacro_GetPropertyValue_3340082741257733700(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e80b0127aL, 0x2e5a5b8e80b0151cL, "min"));
  }
  public static Object propertyMacro_GetPropertyValue_3340082741257733708(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e80b0127aL, 0x2e5a5b8e80b016e8L, "default"));
  }
  public static Object propertyMacro_GetPropertyValue_3340082741257733716(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e80b0127aL, 0x2e5a5b8e80b01660L, "max"));
  }
  public static Object propertyMacro_GetPropertyValue_8335610756436588195(final PropertyMacroContext _context) {
    String result = SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e811ca259L, 0x2e5a5b8e811ca25cL, "target")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    if (result != null) {
      result = result.replaceAll("[^_\\p{Alnum}]", "");
    } else {
      result = "";
    }
    return "sound_" + result;
  }
  public static Object propertyMacro_GetPropertyValue_8335610756436449457(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e811ca259L, 0x2e5a5b8e811ca25dL, "targetPort")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object referenceMacro_GetReferent_3340082741253820292(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "SynthCtrlDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741253847476(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "SynthCtrlDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741253848374(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "SynthCtrlDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741253851414(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "SynthModelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741254007082(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "SynthViewDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741253885400(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "SynthModelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741257396279(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "SoundModuleDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741253800372(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "SynthIntfDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741257411627(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "SoundModuleDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741257411957(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "SoundModuleDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741249889338(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "knobModelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250103148(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "knobDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250114497(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "knobPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250161271(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "knobDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250161604(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "knobPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250161846(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "knobPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741251034004(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc63c92L, "SynthLang.structure.SubPanel"), false, false), "subPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250392940(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "sliderDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250410019(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "sliderPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250428532(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "sliderLabelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250445168(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "sliderLabelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250445452(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "sliderLabelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250423574(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "sliderPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250407148(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "sliderDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250423835(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "sliderPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741251075592(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc63c92L, "SynthLang.structure.SubPanel"), false, false), "subPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250425862(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "sliderPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3347507059715335600(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "LayoutConstrDeclaration");
  }
  public static Object referenceMacro_GetReferent_3347507059715376051(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "LayoutConstrDeclaration");
  }
  public static Object referenceMacro_GetReferent_3347507059715376299(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "LayoutConstrDeclaration");
  }
  public static Object referenceMacro_GetReferent_3347507059715376480(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "LayoutConstrDeclaration");
  }
  public static Object referenceMacro_GetReferent_3347507059715376949(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "LayoutConstrDeclaration");
  }
  public static Object referenceMacro_GetReferent_3347507059715315326(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "subPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3347507059715377194(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "LayoutConstrDeclaration");
  }
  public static Object referenceMacro_GetReferent_3347507059715377421(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "LayoutConstrDeclaration");
  }
  public static Object referenceMacro_GetReferent_3347507059715386862(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "LayoutConstrDeclaration");
  }
  public static Object referenceMacro_GetReferent_3347507059715415329(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "subPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3347507059715419775(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "subPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741251029219(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "subPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741251098430(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc63c92L, "SynthLang.structure.SubPanel"), false, false), "subPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741257737958(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "SoundModuleDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741257733678(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object referenceMacro_GetReferent_3340082741257733686(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cd4aL, "SynthLang.structure.AbstractSound"), false, false), "SoundModuleDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741257794666(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cd74L, 0x2e5a5b8e80be1ebfL, "source")), "SoundModuleDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741257801818(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cd74L, 0x2e5a5b8e80be1f42L, "target")), "SoundModuleDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741257807517(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cd74L, 0x2e5a5b8e80be1f95L, "targetPort")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static boolean ifMacro_Condition_3340082741257523384(final IfMacroContext _context) {
    return false;
  }
  public static boolean ifMacro_Condition_3340082741258889890(final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(_context.getNode(), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cd74L, "SynthLang.structure.Connection"));
  }
  public static boolean ifMacro_Condition_3340082741257285107(final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(_context.getNode(), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e80c2596aL, "SynthLang.structure.SoundLineOut"));
  }
  public static boolean ifMacro_Condition_3340082741257406973(final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(_context.getNode(), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e80c2596aL, "SynthLang.structure.SoundLineOut"));
  }
  public static boolean ifMacro_Condition_3340082741250890630(final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(SNodeOperations.getParent(_context.getNode()), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc63c92L, "SynthLang.structure.SubPanel"));
  }
  public static boolean ifMacro_Condition_3340082741250837826(final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(SNodeOperations.getParent(_context.getNode()), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc63c92L, "SynthLang.structure.SubPanel"));
  }
  public static boolean ifMacro_Condition_3340082741251098418(final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(SNodeOperations.getParent(_context.getNode()), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc63c92L, "SynthLang.structure.SubPanel"));
  }
  public static SNode sourceNodeQuery_3340082741259080020(final SourceSubstituteMacroNodeContext _context) {
    List<SNode> connections = SLinkOperations.getChildren(SLinkOperations.getTarget(SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, "SynthLang.structure.Synthesizer"), false, false), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, 0x43fe12378cc7d4e5L, "connections")), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d4ecL, 0x43fe12378cc86b65L, "connections"));
    for (SNode c : ListSequence.fromList(connections)) {
      if (SNodeOperations.isInstanceOf(c, MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e811ca259L, "SynthLang.structure.ControlConnection"))) {
        SNode n = (SNode) c;
        if (SPropertyOperations.getString(SLinkOperations.getTarget(n, MetaAdapterFactory.getReferenceLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e811ca259L, 0x2e5a5b8e811ca25bL, "source")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) == SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"))) {
          return n;
        }
      }
    }
    return ListSequence.fromList(connections).first();
  }
  public static SNode sourceNodeQuery_3347507059715598039(final SourceSubstituteMacroNodeContext _context) {
    List<SNode> connections = SLinkOperations.getChildren(SLinkOperations.getTarget(SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, "SynthLang.structure.Synthesizer"), false, false), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, 0x43fe12378cc7d4e5L, "connections")), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d4ecL, 0x43fe12378cc86b65L, "connections"));
    for (SNode c : ListSequence.fromList(connections)) {
      if (SNodeOperations.isInstanceOf(c, MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e811ca259L, "SynthLang.structure.ControlConnection"))) {
        SNode n = (SNode) c;
        if (SPropertyOperations.getString(SLinkOperations.getTarget(n, MetaAdapterFactory.getReferenceLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e811ca259L, 0x2e5a5b8e811ca25bL, "source")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) == SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"))) {
          return n;
        }
      }
    }
    return ListSequence.fromList(connections).first();
  }
  public static Iterable<SNode> sourceNodesQuery_3340082741250095058(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, 0x43fe12378cc7ccf4L, "userInterface")), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x4854ee8f94deb9daL, 0x4854ee8f94dec597L, "contents"));
  }
  public static Iterable<SNode> sourceNodesQuery_3340082741256641851(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, 0x43fe12378cc7d4e0L, "sounds")), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d50bL, 0x43fe12378cc86b5eL, "sounds"));
  }
  public static Iterable<SNode> sourceNodesQuery_3340082741256626030(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, 0x43fe12378cc7d4e0L, "sounds")), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d50bL, 0x43fe12378cc86b5eL, "sounds"));
  }
  public static Iterable<SNode> sourceNodesQuery_3340082741257660183(final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, 0x43fe12378cc7d4e0L, "sounds")), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d50bL, 0x43fe12378cc86b5eL, "sounds"))).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getChildren(it, MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x2e5a5b8e80c25889L, 0x2e5a5b8e80c524f3L, "inputPorts"));
      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_3340082741257972003(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, 0x43fe12378cc7d4e5L, "connections")), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d4ecL, 0x43fe12378cc86b65L, "connections"));
  }
  public static Iterable<SNode> sourceNodesQuery_3340082741257012322(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, 0x43fe12378cc7d4e0L, "sounds")), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d50bL, 0x43fe12378cc86b5eL, "sounds"));
  }
  public static Iterable<SNode> sourceNodesQuery_3340082741257402443(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, 0x43fe12378cc7d4e0L, "sounds")), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7d50bL, 0x43fe12378cc86b5eL, "sounds"));
  }
  public static Iterable<SNode> sourceNodesQuery_3340082741250982656(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc63c92L, 0x43fe12378cc7d158L, "controls"));
  }
}
