package SynthLang.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.generator.template.IfMacroContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

@Generated
public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_3340082741245520612(final PropertyMacroContext _context) {
    String result = SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    if (result != null) {
      result = result.replaceAll("[^_\\p{Alnum}]", "");
      if (result.substring(0, 1).matches("\\p{Digit}")) {
        result = "_" + result;
      }
    } else {
      result = "Synthetica";
    }
    return result;
  }
  public static Object propertyMacro_GetPropertyValue_3340082741250213399(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_3340082741245607651(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_3340082741249818934(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, 0x43fe12378cc7ccf4L, "userInterface")), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x4854ee8f94deb9daL, 0x4854ee8f94dec2c8L, "width"));
  }
  public static Object propertyMacro_GetPropertyValue_3340082741249834178(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, 0x43fe12378cc7ccf4L, "userInterface")), MetaAdapterFactory.getProperty(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x4854ee8f94deb9daL, 0x4854ee8f94dec2f7L, "height"));
  }
  public static Object propertyMacro_GetPropertyValue_3340082741245531120(final PropertyMacroContext _context) {
    String result = SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    if (result != null) {
      result = result.replaceAll("[^_\\p{Alnum}]", "");
      if (result.substring(0, 1).matches("\\p{Digit}")) {
        result = "_" + result;
      }
    } else {
      result = "Synthetica";
    }
    return result + "View";
  }
  public static Object propertyMacro_GetPropertyValue_3340082741245521718(final PropertyMacroContext _context) {
    String result = SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    if (result != null) {
      result = result.replaceAll("[^_\\p{Alnum}]", "");
      if (result.substring(0, 1).matches("\\p{Digit}")) {
        result = "_" + result;
      }
    } else {
      result = "Synthetica";
    }
    return result + "Controller";
  }
  public static Object propertyMacro_GetPropertyValue_3340082741245498499(final PropertyMacroContext _context) {
    String result = SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    if (result != null) {
      result = result.replaceAll("[^_\\p{Alnum}]", "");
      if (result.substring(0, 1).matches("\\p{Digit}")) {
        result = "_" + result;
      }
    } else {
      result = "Synthetica";
    }
    return "I" + result;
  }
  public static Object propertyMacro_GetPropertyValue_3340082741245526486(final PropertyMacroContext _context) {
    String result = SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    if (result != null) {
      result = result.replaceAll("[^_\\p{Alnum}]", "");
      if (result.substring(0, 1).matches("\\p{Digit}")) {
        result = "_" + result;
      }
    } else {
      result = "Synthetica";
    }
    return result + "Model";
  }
  public static Object propertyMacro_GetPropertyValue_3340082741249862205(final PropertyMacroContext _context) {
    return _context.createUniqueName("knobInputModel", null);
  }
  public static Object propertyMacro_GetPropertyValue_3340082741250101044(final PropertyMacroContext _context) {
    return _context.createUniqueName("knob", null);
  }
  public static Object propertyMacro_GetPropertyValue_3340082741250088016(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_3340082741250113132(final PropertyMacroContext _context) {
    return _context.createUniqueName("knobPanel", null);
  }
  public static Object propertyMacro_GetPropertyValue_3340082741250337361(final PropertyMacroContext _context) {
    return _context.createUniqueName("slider", null);
  }
  public static Object propertyMacro_GetPropertyValue_3340082741250407510(final PropertyMacroContext _context) {
    return _context.createUniqueName("sliderPanel", null);
  }
  public static Object propertyMacro_GetPropertyValue_3340082741250426081(final PropertyMacroContext _context) {
    return _context.createUniqueName("sliderLabel", null);
  }
  public static Object propertyMacro_GetPropertyValue_3340082741251010928(final PropertyMacroContext _context) {
    return _context.createUniqueName("subPanel", null);
  }
  public static Object referenceMacro_GetReferent_3340082741249889338(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "knobModelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250103148(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "knobDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250114497(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "knobPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250161271(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "knobDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250161604(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "knobPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250161846(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "knobPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741251034004(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc63c92L, "SynthLang.structure.SubPanel"), false, false), "subPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250392940(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "sliderDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250410019(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "sliderPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250428532(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "sliderLabelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250445168(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "sliderLabelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250445452(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "sliderLabelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250423574(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "sliderPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250407148(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "sliderDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250423835(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "sliderPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741251075592(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc63c92L, "SynthLang.structure.SubPanel"), false, false), "subPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741250425862(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "sliderPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741251015943(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "subPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741251029219(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "subPanelDeclaration");
  }
  public static Object referenceMacro_GetReferent_3340082741251098430(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc63c92L, "SynthLang.structure.SubPanel"), false, false), "subPanelDeclaration");
  }
  public static boolean ifMacro_Condition_3340082741250890630(final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(SNodeOperations.getParent(_context.getNode()), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc63c92L, "SynthLang.structure.SubPanel"));
  }
  public static boolean ifMacro_Condition_3340082741250837826(final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(SNodeOperations.getParent(_context.getNode()), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc63c92L, "SynthLang.structure.SubPanel"));
  }
  public static boolean ifMacro_Condition_3340082741251098418(final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(SNodeOperations.getParent(_context.getNode()), MetaAdapterFactory.getConcept(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc63c92L, "SynthLang.structure.SubPanel"));
  }
  public static Iterable<SNode> sourceNodesQuery_3340082741250095058(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc7cc9eL, 0x43fe12378cc7ccf4L, "userInterface")), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x4854ee8f94deb9daL, 0x4854ee8f94dec597L, "contents"));
  }
  public static Iterable<SNode> sourceNodesQuery_3340082741250982656(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x4367d71c7d554642L, 0x8148026aeb16dfebL, 0x43fe12378cc63c92L, 0x43fe12378cc7d158L, "controls"));
  }
}
