package SynthLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.PropertySupport;
import java.util.Iterator;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class PortHasConfig_enum_PropertySupport extends PropertySupport {
  public boolean canSetValue(String value) {
    if (value == null) {
      return true;
    }
    Iterator<PortHasConfig_enum> constants = ListSequence.fromList(PortHasConfig_enum.getConstants()).iterator();
    while (constants.hasNext()) {
      PortHasConfig_enum constant = constants.next();
      if (value.equals(constant.getName())) {
        return true;
      }
    }
    return false;
  }
  public String toInternalValue(String value) {
    if (value == null) {
      return null;
    }
    Iterator<PortHasConfig_enum> constants = ListSequence.fromList(PortHasConfig_enum.getConstants()).iterator();
    while (constants.hasNext()) {
      PortHasConfig_enum constant = constants.next();
      if (value.equals(constant.getName())) {
        return constant.getValueAsString();
      }
    }
    return null;
  }
  public String fromInternalValue(String value) {
    PortHasConfig_enum constant = PortHasConfig_enum.parseValue(value);
    if (constant != null) {
      return constant.getName();
    }
    return "";
  }
}
