package SynthLang.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum PortHasConfig_enum {
  _no_configuration_("<no configuration>", false),
  configuration("configuration", true);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final boolean myValue;
  PortHasConfig_enum(String name, boolean value) {
    myName = name;
    myValue = value;
  }
  public boolean getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Boolean.toString(myValue);
  }
  public static List<PortHasConfig_enum> getConstants() {
    List<PortHasConfig_enum> list = ListSequence.fromList(new LinkedList<PortHasConfig_enum>());
    ListSequence.fromList(list).addElement(PortHasConfig_enum._no_configuration_);
    ListSequence.fromList(list).addElement(PortHasConfig_enum.configuration);
    return list;
  }
  public static PortHasConfig_enum getDefault() {
    return PortHasConfig_enum._no_configuration_;
  }
  public static PortHasConfig_enum parseValue(String value) {
    if (value == null) {
      return PortHasConfig_enum.getDefault();
    }
    if (value.equals(PortHasConfig_enum._no_configuration_.getValueAsString())) {
      return PortHasConfig_enum._no_configuration_;
    }
    if (value.equals(PortHasConfig_enum.configuration.getValueAsString())) {
      return PortHasConfig_enum.configuration;
    }
    return PortHasConfig_enum.getDefault();
  }
}
