package SynthLang.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum SliderOrientation_enum {
  HORIZONTAL("HORIZONTAL", "\"HORIZONTAL\""),
  VERTICAL("VERTICAL", "\"VERTICAL\"");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private SliderOrientation_enum(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<SliderOrientation_enum> getConstants() {
    List<SliderOrientation_enum> list = ListSequence.fromList(new LinkedList<SliderOrientation_enum>());
    ListSequence.fromList(list).addElement(SliderOrientation_enum.HORIZONTAL);
    ListSequence.fromList(list).addElement(SliderOrientation_enum.VERTICAL);
    return list;
  }
  public static SliderOrientation_enum getDefault() {
    return SliderOrientation_enum.HORIZONTAL;
  }
  public static SliderOrientation_enum parseValue(String value) {
    if (value == null) {
      return SliderOrientation_enum.getDefault();
    }
    if (value.equals(SliderOrientation_enum.HORIZONTAL.getValueAsString())) {
      return SliderOrientation_enum.HORIZONTAL;
    }
    if (value.equals(SliderOrientation_enum.VERTICAL.getValueAsString())) {
      return SliderOrientation_enum.VERTICAL;
    }
    return SliderOrientation_enum.getDefault();
  }
}
