package SynthLang.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class ConstraintsAspectDescriptor implements jetbrains.mps.smodel.runtime.ConstraintsAspectDescriptor {
  public ConstraintsAspectDescriptor() {
  }
  public ConstraintsDescriptor getDescriptor(SConceptId conceptId) {
    long id = conceptId.getIdValue();
    if (id == 0x43fe12378cc7cc9eL) {
      return new Synthesizer_Constraints();
    }
    if (id == 0x43fe12378cc7cd74L) {
      return new Connection_Constraints();
    }
    if (id == 0x43fe12378cc7cd4aL) {
      return new AbstractSound_Constraints();
    }
    if (id == 0x2e5a5b8e811ca259L) {
      return new ControlConnection_Constraints();
    }
    return new BaseConstraintsDescriptor(conceptId);
  }
}
