package SynthLang.behavior;

/*Generated by MPS */


/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class SoundConnectionAdd_BehaviorDescriptor extends AbstractSound_BehaviorDescriptor implements IHasInputPort_BehaviorDescriptor, IHasOutputPort_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "SynthLang.structure.SoundConnectionAdd";
  }

}
