package SynthLang.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.ScopeProvider_BehaviorDescriptor;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class SubPanel_BehaviorDescriptor extends AbstractGuiElement_BehaviorDescriptor implements IPanel_BehaviorDescriptor, ScopeProvider_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "SynthLang.structure.SubPanel";
  }

}
